### ISSUE TITLE
BP Beta Tester always show the notices after updating the BuddyPress plugin

### ISSUE THREAD

**Issue by murshed** [buddypress/bp-beta-tester#1]
After updating the Beta Plugin, the update notices always shown on the plugin page.

Screenshot: https://i.imgur.com/VRIpjIJ.png

First reported on: https://buddypress.trac.wordpress.org/ticket/8176

**Comment by imath** [comment]
Thanks for reporting the issue here. I’ll look at it asap.

**Comment by imath** [comment]
I've tested on multisite and I wasn't able to reproduce. Testing on a regular site asap.

**Comment by imath** [comment]
Hum same result.. Weird..

So on both config, here's what I do.

1. Deactivate BuddyPress
1. Go to the BP Beta Tester Admin page
1. Click on the Upgrade to 5.1.0-beta tab
1. I'm redirected on site.url/wp-admin/update.php
1. While it's downloading/installing there's the orange span containing a `1` which is fine as we are simulating an upgrade.
1. Once the installation is over and I go on the Plugins administration page, the orange span is no more displayed.

![Capture d’écran 2019-12-05 à 18 44 31](https://user-images.githubusercontent.com/1834524/70259929-89548000-178f-11ea-8a86-bd6fe9d90a33.png)


Question: if you go on the WordPress Updates screen (as shown above) and force an update check clicking on the "Check Again" button, is the orange span disappearing ?

**Comment by imath** [comment]
Update, this commit https://github.com/buddypress/bp-beta-tester/commit/6f4495b709d311b9cdf696d90e460885479f03a3 should definitively fix this issue.
