### ISSUE TITLE
Deprecated function error

### ISSUE THREAD

**Issue by vapvarun** [buddypress/bp-beta-tester#4]
Deprecated	Creation of dynamic property BP_Beta_Tester::$version is deprecated	
wp-content/plugins/bp-beta-tester/inc/globals.php:20

Deprecated	Creation of dynamic property BP_Beta_Tester::$dir is deprecated	
wp-content/plugins/bp-beta-tester/inc/globals.php:23

Deprecated	Creation of dynamic property BP_Beta_Tester::$inc_path is deprecated	
wp-content/plugins/bp-beta-tester/inc/globals.php:24

Deprecated	Creation of dynamic property BP_Beta_Tester::$css_url is deprecated	
wp-content/plugins/bp-beta-tester/inc/globals.php:27

**Comment by imath** [comment]
Hi @vapvarun 

Thanks a lot for your report. I'll fix it asap.
