### ISSUE TITLE
PHP Deprecated: uksort() Returning bool from comparison function in bp-beta-tester plugin

### ISSUE THREAD

**Issue by vapvarun** [buddypress/bp-beta-tester#8]
While using the bp-beta-tester plugin, a deprecation notice appears related to the uksort() function. 

PHP Deprecated: uksort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in ..\wp-content\plugins\bp-beta-tester\inc\functions.php on line 253

**Comment by vapvarun** [comment]
![image (9)](https://github.com/buddypress/bp-beta-tester/assets/334343/c5d8ba52-dee3-48f1-b9b0-163897fcc6a2)

**Comment by emaralive** [comment]
It appears that an upgrade to version 1.3.0 was not completed, currently the trunk is at 1.3.0-alpha, of which PR #7  had fixed what has been reported by this issue (Deprecated Notice: uksort()). 

Trunk fixes the reported issue, furthermore tested with WP 6.5.5 & WP 6.6-RC2.

Actions to be taken appear to be:

- Update relevant info in [class-bp-beta-tester.php](https://github.com/buddypress/bp-beta-tester/blob/trunk/class-bp-beta-tester.php)
- Update relevant info in [readme.txt](https://github.com/buddypress/bp-beta-tester/blob/trunk/readme.txt).
- Draft a new release & provide a zip file.
- Update wordpress.org plugin directory with new version.

**Comment by imath** [comment]
Thanks for looking into it @emaralive working on it asap
